### ISSUE TITLE
Wirebox mapping not working

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/hyper#14]
I'm unclear on how to use hyper in a CB6 application.  I've tried following the docs and it's just not clear.  I've set up wirebox like this:  https://www.screencast.com/t/U6DOdsUHN6p  but get this after a fwreinit:  https://www.screencast.com/t/VWo1NYoPBA  I'm trying to do this: https://developers.hubspot.com/docs/api/crm/contacts ( List example - python is easiest to map )

How do I configure a hyper instance for use in this model with a base URL, accept header and an apikey query param that gets sent on every request? 

And is this the best place to ask for this kind of help?

**Comment by elpete** [comment]
When you create a WireBox mapping, that is the name in the `inject` attribute of the property.  So in your handler currently you are not injecting your new API wrapper, but the normal Hyper Builder.  Then you are calling a non-existent variable (because it wasn't injected).  Swap `property name="hyper" inject="HyperBuilder@hyper";` with `property name="hubspotAPI" inject="hubspotAPI";` to fix the missing variable.

The final piece would be to use `queryParams` instead of `withQueryParams` in the `initWith` call.  The keys can be any property on a HyperRequest.

**Comment by Daemach** [comment]
The component seems to be working now, but it doesn't look like the key is getting passed.  https://boxteam.slack.com/archives/C052RTJ34/p1591977073017300

Is there any way to debug this?  A flag that dumps to systemoutput or any other way to see what is getting sent?
